version: "3.7"
services:
  elasticsearch:
    image: elasticsearch:8.11.0
    ports:
      - "9200:9200"
    environment:
      xpack.security.enabled: "false"
      discovery.type: "single-node"
      ES_JAVA_POTS: "-Xms256m -Xmx256m"
      # node.name: "node1"
      # cluster.initial_master_nodes: "['node1']" 
      # cluster.name: "elasticsearch"
      # ingest.geoip.downloader.enabled: "false"
      # http.cors.enabled: "true"
      # http.cors.allow-origin: "*" 
    # healthcheck: # 添加健康检测
    #   test: ["CMD", "curl", "-f", "http://localhost:9200"]
    #   interval: 30s
    #   timeout: 3s
    #   retries: 3
    #   start_period: 40s
    # volumes:
    #   - ./es-data:/usr/share/elasticsearch/data
    #   - ./es-log:/usr/share/elasticsearch/logs