version: "3.8"
services:
  elasticsearch:
    image: elasticsearch:8.11.0
    # volumes:
    #   - ./es-data:/usr/share/elasticsearch/data
    #   - ./es-log:/usr/share/elasticsearch/logs
    # privileged: true
    ports:
      - "9200:9200"
    # restart: "always"
    environment:
      xpack.security.enabled: "false"
      discovery.type: "single-node"
      ES_JAVA_POTS: "-Xms256m -Xmx256m"
      # node.name: "node1"
      # cluster.initial_master_nodes: "['node1']" 
      # cluster.name: "elasticsearch"
      # ingest.geoip.downloader.enabled: "false"
      # http.cors.enabled: "true"
      # http.cors.allow-origin: "*"

    healthcheck: # 添加健康检测
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s

  logstash:
    image: logstash:8.11.0
    volumes:
      - ./logstash.conf:/etc/logstash.conf
    links: 
     -  elasticsearch
    command: ["logstash", "-f", "/etc/logstash.conf"]
    ports:
       - "5400:5400"
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      xpack.monitoring.enabled: "true"


  kibana:
     image: kibana:8.11.0
     ports:
        - "5601:5601"
     depends_on:
      elasticsearch:
        condition: service_healthy
     links:          
        -  elasticsearch 
     environment:
        ELASTICSEARCH_URL: http://elasticsearch:9200 
     

  nginx:
      image: nginx
      ports:
        - "9080:80"
      logging:
        driver: "syslog"
        options:
          syslog-address: "tcp://localhost:514"
          tag: "nginx"
      