version: "3.8"
services:
  elasticsearch:
    image: elasticsearch:8.11.0
    ports:
      - "9200:9200"
    # networks:
    #   - elastic
    environment:
      discovery.type: "single-node"
      cluster.name: "elasticsearch"
      ES_JAVA_POTS: "-Xms256m -Xmx256m"
      xpack.security.enabled: "false"
      # node.name: "node1"
      # cluster.initial_master_nodes: "['node1']" 
      # ingest.geoip.downloader.enabled: "false"
      # http.cors.enabled: "true"
      # http.cors.allow-origin: "*" 
    # healthcheck: # 添加健康检测
    #   test: ["CMD", "curl", "-f", "http://localhost:9200"]
    #   interval: 30s
    #   timeout: 3s
    #   retries: 3
    #   start_period: 40s
    # volumes:
    #   - ./es-data:/usr/share/elasticsearch/data
    #   - ./es-log:/usr/share/elasticsearch/logs

  logstash:
    image: logstash:8.11.0
    volumes:
      - ./logstash.conf:/etc/logstash.conf
    links: 
     -  elasticsearch
    command: ["logstash", "-f", "/etc/logstash.conf"]
    ports:
       - "5400:5400"
    depends_on:
     -  elasticsearch #:
        # condition: service_healthy
    environment:
      xpack.monitoring.enabled: "true"
    # networks:
    #   - elastic

  kibana:
     image: kibana:8.11.0
     ports:
        - "5601:5601"
     depends_on:
      - elasticsearch #:
        # condition: service_healthy
     links:          
        -  elasticsearch 
     environment:
        ELASTICSEARCH_URL: http://elasticsearch:9200 
    #  networks:
    #   - elastic    

  nginx:
      image: nginx
      ports:
        - "9080:80"
      logging:
        driver: "syslog"
        options:
          syslog-address: "tcp://localhost:514"
          tag: "nginx"
    
# networks:
#   elastic:
#     driver: bridge